### ISSUE TITLE
[FEAT] Match time format of ContentsView in HomeFragment, ContentsSimpleActivity

### ISSUE THREAD

**Issue by yubinquitous** [TeamHavit/Havit-Android#105]
**📝 DESCRIPTION**
- Date : 2022.01.18

**☑ TODO**
- [x] HomeFragment 최근 저장 콘텐츠 시간 형식 맞추기
- [x] ContentsSimpleActivity 콘텐츠 저장시간 형식 맞추기
- [x] ContentsSimpleActivity 콘텐츠 알림시간 형식 맞추기
- [x] ContentsSimpleActivity 콘텐츠 알림 없을 경우 visibility 설정
