### ISSUE TITLE
[FEAT/UI] Create Contents Order Bottom Sheet Dialog

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#109]
**📝 DESCRIPTION**
- Date : 2022.01.18

**☑ TODO**
- [x] 콘텐츠 정렬 바텀시트다이얼로그 UI 제작
- [x] 선택된 정렬의 배경, 글자 색 바꾸기
- [x] 최신순 text 누를 시 기능 제작
- [x] 서버 통신을 통해 정렬 바뀌게 조정
