### ISSUE TITLE
[FEAT] Connect Havit Button with Server

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#120]
**📝 DESCRIPTION**
- Date : 2022.01.19

**☑ TODO**
- [x] 읽은 item인 경우 해빗 버튼 설정
- [x] 어뎁터에 있는 onclick함수를 interface를 사용하여 activity로 빼기
- [x] 해빗 버튼 누를 시 서버 patch 사용
