### ISSUE TITLE
[FEAT/UI/FIX] Set Default Image & Fix Havit Button

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#137]
**📝 DESCRIPTION**
- Date : 2022.01.19
에러사항 : 어쩌다 가끔 해빗 버튼을 눌러도 자동으로 다시 바껴버리는 에러가 발생함

**☑ TODO**
- [x] 기본 이미지 일때와 서버에서 이미지 줄 때 구분해서 콘텐츠 아이템에 바인딩
- [x] 해빗 버튼 체크가 다른 아이템에 전달되지 않는 에러 해결 -> 클릭마다 patch만 했던 것에서 get도 하니 해결
- [x] 콘텐츠 뷰 이미지 로드 시 크게 보이는 부분 해결 -> 고정 dp 사용 (그러나 확대되는 문제점 발생)
