### ISSUE TITLE
[FEAT] Set recyclerView itemClickListener in HomeFragment, ContentsSimpleActivity

### ISSUE THREAD

**Issue by yubinquitous** [TeamHavit/Havit-Android#147]
**📝 DESCRIPTION**
- Date : 2022.01.20

**☑ TODO**
- [x] **HomeFragment** → category item 클릭 이벤트
- [x] **HomeFragment** → 최근저장콘텐츠 클릭 이벤트
- [x] **ContentsSimpleActivity** → 아이템 클릭 이벤트
- [x] **ContentsSimpleActivity** → empty일 경우 콘텐츠 추가 클릭 이벤트
- [x] **ContentsSimpleActivity** → 해빗하기 버튼 클릭 이벤트
