### ISSUE TITLE
[FEAT] 공유프로세스 화면 이동

### ISSUE THREAD

**Issue by KxxHyoRim** [TeamHavit/Havit-Android#149]
**📝 DESCRIPTION**
- Date : 2022.01.20 ~ 21

**☑ TODO**
- [ ] BottomSheetFragment 에서 카테고리 개수 검사
      - 개수가 0이면 noCategoryFragment 로 이동
      - 이외의 경우에는 chooseCategory Fragment로 이동
- [ ]  SelectCategoryFragment에서 카테고리 추가 누를 시 addCategoryFragmet 로 이동
- [ ] SelectCategoryFragment 리사이클러뷰에 클릭 이벤트 넣고 색깔 처리
- [ ] 데이터 관리
