### ISSUE TITLE
[FEAT] Create Adapter for Category View & Apply MVVM

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#15]
**📝 DESCRIPTION**
- Date : 2020.01.12

**☑ TODO**
- [x] CategoryView에 대한 Adapter 생성
- [x] CategoryFragment의 ViewModel 생성
- [x] CategoryFragment에 mvvm 적용
