### ISSUE TITLE
[FEAT] 공유 프로세스 서버 연동

### ISSUE THREAD

**Issue by KxxHyoRim** [TeamHavit/Havit-Android#150]
**📝 DESCRIPTION**
- Date : 2022.01.20-21

**☑ TODO**
- [ ] BottomSheetShareFragment 카테고리 개수 get
- [ ] 카테고리 생성 서버 연동
- [ ] 컨텐츠 추가 서버 연동
- [ ] 더보기에서 연결 될 때 수정 프로세스 서버 연동
