### ISSUE TITLE
[FEAT/UI] 카테고리 순서 수정 뷰 서버 연결 및 삭제 구현

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#157]
**📝 DESCRIPTION**
- Date : 2022.01.20

**☑ TODO**
- [x] 카테고리 수정 뷰에서 서버 통신하여 카테고리 리스트 불러오기
- [x] 카테고리 삭제 버튼 눌렀을 시 순서 유지하며 리스트에서 삭제 되게끔
- [x] 카테고리 내용 수정 뷰에서 제목 edit text 선택 시 커서 색 및 텍스트 색 변경
- [x] 카테고리 제목 수정 시 반영되게 클라 구현
