### ISSUE TITLE
[FEAT] Create Adapter for Contents View & Apply MVVM

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#19]
**📝 DESCRIPTION**
- Date : 2020.01.12

**☑ TODO**
- [x] ContentsFragment에 대한 adapter 생성
- [x] ContentsViewModel 생성
- [x] fragment_contents에 databinding
- [x] ContentsFragment에 MVVM 적용

**Comment by kimhyeing** [comment]
(풀리퀘 안떠서 코드로 merge하고 push하고 닫습니다..)
