### ISSUE TITLE
[CHORE/UI] 카테고리 bottom dp 조정 및 폰트 지정

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#255]
**📝 DESCRIPTION**
- Date : 2022.02.05

**☑ TODO**
- [x] 카테고리 전체 뷰 리사이클러 뷰 하단 dp 조정
- [x] 카테고리 관리 뷰 리사이클러 뷰 하단 dp 조정
- [x] 쓸데없는 파일(CategoryContentsModifyFragment & xml) 삭제
