### ISSUE TITLE
[FEAT/UI] 콘텐츠 뷰의 상단 카테고리 명 누를 시 뜨는 탑바텀시트 다이얼로그 제작

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#258]
**📝 DESCRIPTION**
- Date : 2022.02.06

**☑ TODO**
- [x] 애니메이션 파일 작성
- [x] 기존 BottomSheetFragment -> DialogFragment로 교체
- [x] 다이얼로그 애니메이션 적용 (등장 시)
- [ ] 다이얼로그 애니메이션 적용 (사라질 시)
- [x] 스크롤 바 적용
- [x] 리사이클러뷰 하단 패딩 조정
