### ISSUE TITLE
[FEAT] 전체 카테고리 스크롤이 밀리는 현상 해결

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#260]
**📝 DESCRIPTION**
- Date : 2022.02.

**☑ TODO**
- [x] 카테고리 순서 변경시 전체 카테고리 뷰에서 스크롤이 밀리는 현상을 해결 -> ListAdapter 사용
- [x] 여전히 스크롤이 밀려 notifyDataSetChanged()로 교체
- [x] notifyDataSetChanged의 깜빡임 현상을 setHasStableIds(true)를 통해 해결
