### ISSUE TITLE
[FEAT] 카테고리 추가 시 중복 검색

### ISSUE THREAD

**Issue by KxxHyoRim** [TeamHavit/Havit-Android#267]
**📝 DESCRIPTION**
- Date : 2022.02.08

**☑ TODO**
- [ ] 카테고리 추가/생성 시 기존에 존재하는 카테고리명인지 중복 검색
- [ ] 서버통신(get) 추가
- [ ] 중복 검색 코드 추가
