### ISSUE TITLE
[FIX] 메인뷰에 데이터 변경사항 반영

### ISSUE THREAD

**Issue by yubinquitous** [TeamHavit/Havit-Android#298]
**📝 DESCRIPTION**
- Date : 2022.02.16

**☑ TODO**
- [x] user 도달률 반영
- [x] 카테고리 리사이클러뷰 반영
- [x] 최근저장 컨텐츠 리사이클러뷰 반영
- [x] ContentsSimpleActivity에서 뒤로가기 버튼 클릭 시 finish()로 변경
