### ISSUE TITLE
[FEAT] 카테고리 개수 초과 시 카테고리 생성 차단

### ISSUE THREAD

**Issue by KxxHyoRim** [TeamHavit/Havit-Android#299]
**📝 DESCRIPTION**
- Date : 2022.02.16 ~

**☑ TODO**
- [ ] custom toast 제작
- [ ] 기존에 카테고리 목록을 가져오는 서버통신에서 카테고리 개수 추출
- [ ] 코드 단에서 카테고리 개수 초과시 '카테고리 추가'버튼 진입 불가 + custom toast 띄우기
