### ISSUE TITLE
[UI] 메인뷰 디자인 변경사항 적용

### ISSUE THREAD

**Issue by yubinquitous** [TeamHavit/Havit-Android#332]
**📝 DESCRIPTION**
- Date : 2022.02.21

**☑ TODO**
- [x] 상단 해빗 로고 색 변경
- [x] 상단에 알림아이콘 좌측에 서비스가이드 아이콘 추가
- [x] 000님의 카테고리 등등 들어가 있는 흰색 시트 : 라운드값 기존 24에서 16로 변경 (스크롤 할시에 위에 흰색 그라데이션으로- 아요는 라운드값만 변경하면 되고, 안드는 그라데이션으로 변경필요!) 시작색 - white opacity 100 -> opacity 0 
- [x] 각 카테고리 카드 내 제목 폰트 크기 15 semibold로 변경 + 제목,저장콘텐츠, 아이콘 위치값 변경
- [x] 최근 저장 콘텐츠 카테고리명 노출하는 영역에 보라색 원 제거
- [x] 서비스가이드 배너 삭제
