### ISSUE TITLE
[UI] 메인뷰 배경색 변경, 불필요한 constraint layout 삭제

### ISSUE THREAD

**Issue by yubinquitous** [TeamHavit/Havit-Android#358]
**📝 DESCRIPTION**
- Date : 2022.03.01

**☑ TODO**
- [x] sticky scroll 아래의 카테고리뷰 마진값 음수로 수정
- [x] 카테고리뷰 background radius도 16으로 수정
- [x] 메인뷰 전체 배경색 white_gray로 변경
- [x] 메인뷰의 모든 배경색 전면 수정,,
- [x] constraint layout도 삭제 ~
