### ISSUE TITLE
[FEAT/UI] Set Fixed Height on Share Progress

### ISSUE THREAD

**Issue by KxxHyoRim** [TeamHavit/Havit-Android#37]
**📝 DESCRIPTION**
- Date : 2020.01.13

**☑ TODO**
- [x] 공유하기 BottomSheet 높이 고정(0.94)
- [x] EXPANDED된 상태 유지
- [x] skipCollapsed 속성 적용
       HALF_EXPANDED 안거치고 down drag할 수 있도록(부드러운 드래그 모션 지원)
