### ISSUE TITLE
[FEAT] 도달률 팝업 구현

### ISSUE THREAD

**Issue by yubinquitous** [TeamHavit/Havit-Android#373]
**📝 DESCRIPTION**
- Date : 2022.03.06

**☑ TODO**
- [x] 상단 팝업 X 누를 시, 3일 뒤에 다시 노출 (X누른 시간 기준)
- [x] 구간 변경 시(0 ~ 33% -> 34 ~ 66%) 변경 된 구간 팝업 노출
- [x] 만약에 X 누르고 3일이 지나지 않았는데 구간 변경 시 변경된 구간 팝업 노출(3일 만료되지 않더라도 바로 노출)
- [x] 구간별 텍스트 설정
