### ISSUE TITLE
[REFACTOR] 콘텐츠 뷰 순서 dialog를 RadioGroup을 사용하여 리팩토링

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#386]
**📝 DESCRIPTION**
- Date : 2022.03.07

![image](https://user-images.githubusercontent.com/68214704/156983636-acd6e2c1-24ff-4dcf-a9ed-4e5e383fb392.png)
위의 dialog 제작 코드를 radiogroup을 사용하여 refactoring
**☑ TODO**
- [x] 콘텐츠 뷰 순서 변경 bottomsheetdialog를 외부 파일로 제작
- [x] selector.xml 제작
- [x] interface 제작 및 activty에서 함수 정의
