### ISSUE TITLE
[FEAT] 콘텐츠 뷰 스켈레톤 및 shimmer 효과 지정

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#392]
**📝 DESCRIPTION**
- Date : 2022.03.11

![image](https://user-images.githubusercontent.com/68214704/157865674-5d930ec8-28ab-45ca-a8dc-6f2292715f63.png)

스켈레톤 UI 중 반짝이는 효과 (shimmer)가 있는 라이브러리 중 facebook의 라이브러리를 활용
```kotlin
implementation "com.facebook.shimmer:shimmer:0.5.0"
```

사용법 링크 : https://leveloper.tistory.com/214

**☑ TODO**
- [x] 스켈레톤 UI 제작
- [x] 스켈레톤 효과 적용
- [x] 카테고리는 스켈레톤 제거 및 바로 불러오기
