### ISSUE TITLE
[FEAT] 카테고리 추가 뷰 통일

### ISSUE THREAD

**Issue by KxxHyoRim** [TeamHavit/Havit-Android#398]
**📝 DESCRIPTION**
- Date : 2022.03.14

**☑ TODO**
- [ ] 공유프로세스에서 접근하는 **카테고리 추가** 부분과, 앱 내의 전체카테고리 -> **카테고리 추가** 뷰를 통일
- [ ] 혜인이가 앱 내의 카테고리 추가 기능 구현을 위해 작업한 코드가, 내가 작업한 코드와 중복되던 비효율이 존재했음.
- [ ] 이에 혜인이의 코드 (xml과 그에 상응하는 kt 파일)을 지우고, 공유프로세스의 코드로 재활용
- [ ] 뷰 전환에 따라 navigation 코드를 일부 수정함

| 공유프로세스 | 앱 내의 카테고리 뷰 |
|----|----|
| ![image](https://user-images.githubusercontent.com/59546818/158078555-9185b7a4-c52d-4f6e-8c86-4af6f6c0f72a.png) | ![image](https://user-images.githubusercontent.com/59546818/158078704-742934bd-8f28-4aa0-8cd9-6f5ed20480b1.png) |

@sdu07024 확인해주세여~
