### ISSUE TITLE
[FEAT/UI] Initialize Contents View

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#4]
**📝 DESCRIPTION**
- Date : 2020.01.11

**☑ TODO**
- [x] Contents 관련 패키지 및 fragment 생성 및 초기설정
- [x] Adapter & ViewModel 초기설정
- [x] fragment_contents databinding 설정
- [x] item_contents_linear_min 생성
