### ISSUE TITLE
[REFACTOR] #420 코드 리뷰 반영

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#430]
**📝 DESCRIPTION**
- Date : 2022.03.21

**☑ TODO**
- [x] ContentsOrderModifyActivity의 set 변수 삭제
- [x] 변수명 변경 (상수가 아닌 것들 대문자 -> 카멜 표기)
- [x] 변수명 직관적 변경
