### ISSUE TITLE
[FEAT/UI] 카테고리 이름 수정 시 제한 기능 추가 및 키보드 엔터 기능 변경

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#437]
**📝 DESCRIPTION**
- Date : 2022.03.21

기능 추가 완료된 사진
![image](https://user-images.githubusercontent.com/68214704/159426813-63badcc6-e358-4b73-9211-edac1f03b7b6.png)

**☑ TODO**
- [x] 카테고리 명이 비었을 시 완료 버튼 비활성화
- [x] 카테고리 명이 15자를 초과하는 것 막기
- [x] x버튼을 통해 카테고리 명 한번에 지우기
- [x] 키보드 엔터 기능 다음->완료(키보드 내려감) 로 변경
