### ISSUE TITLE
[FEAT/UI] 카테고리 디자인 변경사항 적용 및 카테고리 개수 바인딩 변경

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#440]
**📝 DESCRIPTION**
- Date : 2022.03.22

**☑ TODO**
- [x] 카테고리가 없을 시 디자인 변경사항 적용
- [x] 카테고리 뷰에서 카테고리 개수 바인딩 변수 변경
- [x] 카테고리 없을 때/있을 때 visibility 처리를 xml에서 관리

**Comment by KxxHyoRim** [comment]
이슈 내용 조금더 자세하게 적어주세요!
