### ISSUE TITLE
[FEAT] 공유프로세스 카테고리 없을 시 분기처리

### ISSUE THREAD

**Issue by KxxHyoRim** [TeamHavit/Havit-Android#442]
**📝 DESCRIPTION**
- Date : 2022.03.22

**☑ TODO**
- [x]  공유프로세스 카테고리 없을 시 분기처리
- [x] #443
- [x] #444
- [x] navigation 로직 수정
- [x] include 를 활용하여 2, 3번에서 언급한 layout visibility 처리
