### ISSUE TITLE
[FEAT] 마이페이지 확인한 콘텐츠 클릭 시 콘텐츠 뷰 조정

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#471]
**📝 DESCRIPTION**
- Date : 2022.04.02

![image](https://user-images.githubusercontent.com/68214704/161385641-a6252571-7217-4229-9084-cd7507733ed1.png)
확인한 콘텐츠(카테고리 아이디 : -2)를 눌렀을 시 전환되는 콘텐츠 뷰의 화면 조정 (칩, visibility, clickable 등 조정)

**☑ TODO**
- [x] chip이 봤어요가 선택되어있게 조정
- [x] 수정 버튼 gone
- [x] 카테고리 명 클릭 시 뜨던 topbottomsheet 안나오게끔 조정
- [x] 서버 호출 시 전체 콘텐츠 중 본 콘텐츠만 호출되게끔 조정
