### ISSUE TITLE
[FEAT] Navigate Category View & RecyclerView item Click

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#50]
**📝 DESCRIPTION**
- Date : 2022.01.14

**☑ TODO**
- [x] 카테고리 뷰 전체 페이지에서 관리 페이지 연결
- [x] 관리페이지에 대한 리싸이클러뷰 adapter 생성
- [x] 관리페이지에 대한 리싸이클러뷰 item 클릭 시 내용 수정 화면으로 이동
- [x] 뒤로가기 버튼 눌렀을 시 back 구현
