### ISSUE TITLE
[FIX] dialogUtil 수정

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#517]
**📝 DESCRIPTION**
- Date : 2022.04.26

**☑ TODO**
- [x] string 값 잘못된 부분 수정
- [x] 디자인 잘못된 부분 수정
- [x] 함수 호출 순서 변경 -> 확인 버튼 눌렀을 때 함수 실행 후 dismiss되는 기존 로직에서 dismiss후 함수 실행 로직으로 변경 (호출한 화면의 finish가 이뤄져야하는 경우가 있어, window leak를 방지하기 위해 변경)
