### ISSUE TITLE
[FEAT] 카테고리 뷰 다이얼로그 추가 및 토스트 띄우기

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#522]
**📝 DESCRIPTION**
- Date : 2022.04.30

**☑ TODO**
- [x] 카테고리 순서 변경 뷰 뒤로가기 시 다이얼로그 띄우기
- [x] 카테고리 내용 수정 뷰 뒤로가기 시 다이얼로그 띄우기
- [x] 카테고리 삭제 시 띄워지는 다이얼로그를 DialogUtil을 이용해 refactoring하기
- [x] 카테고리 수정 완료 시 토스트 띄우기
