### ISSUE TITLE
[UI] 환경설정 뷰 수정

### ISSUE THREAD

**Issue by KxxHyoRim** [TeamHavit/Havit-Android#532]
**📝 DESCRIPTION**
- Date : 2022.05.06

**☑ TODO**
![image](https://user-images.githubusercontent.com/59546818/166985735-7d01c5f1-13ae-4272-9a15-8260934867c9.png)

- [x] 버전정보 부분 없앰
- [x] 고객센터 링크 변경
- [x] 기획에서 릴리즈때에는 `공지사항` 비활성화 할거라고함 -> 서비스 준비중 toast설정
- [x] 고객센터 누르면 이메일 전송 화면으로 이동
