### ISSUE TITLE
[FEAT] 알림 환경설정 값에 따른 notification 생성 여부 결정

### ISSUE THREAD

**Issue by KxxHyoRim** [TeamHavit/Havit-Android#535]
**📝 DESCRIPTION**
- Date : 2022.05.10

**☑ TODO**
- [x] SettingPreference에 생성
- [x] SettingAlarmViewModel 생성 & SettingPreference di
- [x] switch 변경될때마다 toggle observe
- [x] FirebaseMessagingService에서 Preference 값 가져옴 -> preference 값에 따라 notification 생성 여부 결정
