### ISSUE TITLE
[UI] 제목수정뷰 EditText 영역 벗어나면 gradient 처리

### ISSUE THREAD

**Issue by KxxHyoRim** [TeamHavit/Havit-Android#585]
**📝 DESCRIPTION**
- Date : 2022.06.08

**☑ TODO**
- [ ] 제목수정뷰 EditText 영역 벗어나면 gradient 처리
- [ ] 아래 동영상 상단 부분 보면 글자가 자연스럽게 사라짐
- [ ] 민영이 만나서 작업하면서 실시간으로 물어봄 ^^

https://user-images.githubusercontent.com/59546818/172549848-2f7d0778-9422-4ee1-af82-e024ad5efab8.mp4
