### ISSUE TITLE
[FEAT] 더보기 뷰 - 카테고리 이동

### ISSUE THREAD

**Issue by KxxHyoRim** [TeamHavit/Havit-Android#594]
**📝 DESCRIPTION**
- Date : 2022.06.10

**☑ TODO**
- [ ] `EditCategoryFromMoreFragment`, `EditCategoryFromMoreViewModel` 추가
- [ ] `RecyclerViewAdapter` 추가
- [ ] 카테고리 데이터 get api 추가
- [ ] 카테고리 patch api 추가

**Comment by KxxHyoRim** [comment]
![image](https://user-images.githubusercontent.com/59546818/173862165-460299a8-7b95-4373-a449-7d7efb449b10.png)
