### ISSUE TITLE
[FEAT] 콘텐츠 뷰 서버 연결 실패 처리

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#598]
**📝 DESCRIPTION**
- Date : 2022.06.12

**☑ TODO**
- [x] 서버 데이터 받아오기 실패 할 시 레이아웃 변경하여 서버 연결 실패했음을 보여줌
- [x] 새로고침을 통해 서버 요청 재시도 처리
- [x] 서버에 수정 요청 등을 실패할 시엔 토스트 띄우기
