### ISSUE TITLE
[FEAT] 카테고리 수정시에만 다이얼로그 표시

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#614]
**📝 DESCRIPTION**
- Date : 2022.06.30

**☑ TODO**
- [x] 카테고리 명 & 이미지가 수정되었는지 판별
- [x] 카테고리 순서 변경되었는지 판별
- [x] 수정된 경우만 뒤로가기 경고 다이얼로그 표시
- [x] 수정되지 않은 경우 finish
