### ISSUE TITLE
[fix] 김효림 담당 부분 버그 고치기

### ISSUE THREAD

**Issue by KxxHyoRim** [TeamHavit/Havit-Android#681]
**📝 DESCRIPTION**
- Date : 2022.08.24

**☑ TODO**
- [x] fcm 앱이 Foreground 상태일때만 푸시 팝업이 뜸
- [x] 알림 완료된 컨텐츠 알림 수정 -> 500 뜨면 toast 띄우기
알림을 재설정하려면 알림 삭제 후 다시 시도해주세요
- [x] 고객센터 - 네이버 메일에서는 수신자 자동완성이 안됨
- [ ] 더보기 - 알림 수정 - 직접 알림 선택을 할 경우 작동 안함
- [x] 푸시알림 이미지 띄우기
