### ISSUE TITLE
[FEAT] 환경설정 / 공유하기 notion 링크 연결

### ISSUE THREAD

**Issue by KxxHyoRim** [TeamHavit/Havit-Android#693]
**📝 DESCRIPTION**
- Date : 2022.08.28

**☑ TODO**
- [ ] 공유하기 notion 링크 연결
- [ ] 보안상의 이유로 webView에서 노션 못띄움
- [ ] 외부 브라우저로 연결
