### ISSUE TITLE
[UI] Set Color & Font

### ISSUE THREAD

**Issue by KxxHyoRim** [TeamHavit/Havit-Android#7]
**📝 DESCRIPTION**
- Date : 2020.01.12
- feature/share branch에서 작업함

**☑ TODO**
- [x] Color 변수 소문자로 통일(snake style)
- [x] Font Family 추가
- [x] Font Style 추가

**Comment by KxxHyoRim** [comment]
+) Color 로 인해서 에러나는 xml파일 color값 수정
