### ISSUE TITLE
[UI] Set ShareActivity UI

### ISSUE THREAD

**Issue by KxxHyoRim** [TeamHavit/Havit-Android#7]
**📝 DESCRIPTION**
- Date : 2021.01.10 ~ 2021.01.11

**☑ TODO**

- [ ] Create ShareAcitivy and Under Fragments
- [ ] Set Navitagion between Fragments
- [ ] Set Url at Fragment
