### ISSUE TITLE
[FIX] 콘텐츠 뷰 에러 수정

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#717]
**📝 DESCRIPTION**
- Date : 2022.09.08

**☑ TODO**
- [x] fix: 카테고리 목록 바텀시트로 콘텐츠 뷰 이동한 경우, 수정 버튼 클릭 시 `imageId` 정보가 넘어가지 않아 발생한 이미지 아이콘 미선택 현상 수정
- [x] fix: 위와 같은 상황에서, 제목과 아이콘을 수정 시 카테고리 목록의 `position`을 넘겨주지 않아 반영 사항이 바텀시트 카테고리 목록의 `0`번 index로 수정이 됨
- [x] fix: 알림 완료 처리 수정

|정상|알림 chip 선택 후 돌아왔을 때|
|:-----:|:-----:|
|<img src="https://user-images.githubusercontent.com/68214704/189037011-8077eebc-9145-450c-aa2a-60330364fd92.png">|<img src="https://user-images.githubusercontent.com/68214704/189037060-b6a48873-cf0a-4473-9734-d08e7256abd9.png">|
