### ISSUE TITLE
[FEAT/UI] Modify UI detail & Set Click Listener

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#74]
**📝 DESCRIPTION**
- Date : 2022.01.16

**☑ TODO**
- [x] 콘텐츠 뷰 알람 칩 선택 시 색 바뀜
- [x] 콘텐츠 뷰 검색창 edit text에서 text로 바꾸기
- [x] 콘텐츠 뷰 item color 바꾸기
- [x] 콘텐츠 뷰 item 사진 radius 조정
- [x] 콘텐츠 뷰 해빗하기 버튼 클릭 리스너 셋팅
