### ISSUE TITLE
[FIX] 메인뷰 포지션 버그 고치기

### ISSUE THREAD

**Issue by yubinquitous** [TeamHavit/Havit-Android#746]
**📝 DESCRIPTION**
- Date : 2022.09.21

**☑ TODO**
- [x] 메인뷰 최근저장콘텐츠 포지션 버그 고치기
- [x] 최근저장/봐야하는 콘텐츠뷰 포지션 버그 고치기
- [x] 알람뷰 포지션 버그 고치기
