### ISSUE TITLE
[CHORE] Sementic Versioning v1.0.0적용

### ISSUE THREAD

**Issue by KxxHyoRim** [TeamHavit/Havit-Android#765]
**📝 DESCRIPTION**
- Date : 2022.10.31

**☑ TODO**
- [x] [Sementic versioning ](https://spoqa.github.io/2012/12/18/semantic-versioning.html)적용
- [x] `feat/manage-version` 브랜치 체크아웃
- [x] build.gradle(:app) 에서 `version code`와 `version name` 수정

@yubinquitous @ny2060 @sdu07024 
앞으로 업데이트를 하는 상황에는 `feat/manage-version` 브랜치에서 작업해보아요!

**Comment by yubinquitous** [comment]
넵 브랜치 화긴했습니다~~
