### ISSUE TITLE
[feat] push api 변경사항 반영

### ISSUE THREAD

**Issue by KxxHyoRim** [TeamHavit/Havit-Android#770]
**📝 DESCRIPTION**
- Date : 2022.11.07

**☑ TODO**
- [ ] isSeen과 contentId 키값 추가
- [ ] push notification 선택 후 webActivity로 연결되는데,
이때 필요한 Extra data 값이 없어서 null값이 일어나는 상황이었음
- [ ] isSeen과 contentId 키값을 추가해주고 extra 값을 넘겨주도록 코드 수정
