### ISSUE TITLE
[REFACTOR] Apply RecyclerView on Icon Item

### ISSUE THREAD

**Issue by KxxHyoRim** [TeamHavit/Havit-Android#78]
**📝 DESCRIPTION**
- Date : 2022.01.16

**☑ TODO**
- [x] Create icon item layout(xml)
- [x] Create data class
- [x] Create ViewHolder
- [x] Set Adapter
- [x] Set RecyclerView
- [x] Set GridLayout
- [x] Apply Adapter on RecyclerView
- [x] Apply data on adapter
- [x] #84
