### ISSUE TITLE
[FEAT] Dev, Prod 서버 분리로 인한 세팅 변경

### ISSUE THREAD

**Issue by KxxHyoRim** [TeamHavit/Havit-Android#788]
**📝 DESCRIPTION**
- Date : 2022.11.22

**☑ TODO**
- [x] Firebase의 새 프로젝트에 'android' 프로젝트 등록
- [x] 새롭게 생성된 `google-services.json` 을 안드로이드 프로젝트에 적재
- [x] flavorDimensions 을 활용해 dev, prod용 `google-services.json`을 분리
- [x] gitIgnore 설정
