### ISSUE TITLE
[FEAT] home화면 ga 적용

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#825]
**📝 DESCRIPTION**
- Date : 2023.04.16

**☑ TODO**
- [x] 봐야하는 콘텐츠 버튼 클릭 시 이벤트 보내기
- [x] 콘텐츠 검색 버튼 클릭 시 이벤트 보내기
- [x] 전체보기(카테고리) 버튼 클릭 시 이벤트 보내기
- [x] 해빗 서비스 이용 방법 버튼 클릭 시 이벤트 보내기
- [x] 더보기(최근저장콘텐츠) 버튼 클릭 시 이벤트 보내기
- [x] 각 사이트 버튼 클릭 시 이벤트 보내기
