### ISSUE TITLE
[FEAT] 바텀네비게이션 3가지 메뉴 & 플로팅버튼(콘텐츠 생성) 클릭 ga 붙이기

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#826]
**📝 DESCRIPTION**
- Date : 2023.04.16

**☑ TODO**
- [x] 바텀 네비게이션 홈 클릭 시 ga 이벤트 보내기
- [x] 바텀 네비게이션 카테고리 클릭 시 ga 이벤트 보내기
- [x] 바텀 네비게이션 마이페이지 클릭 시 ga 이벤트 보내기
- [x] 플로팅 버튼(콘텐츠 생성) 클릭 시 ga 이벤트 보내기
