### ISSUE TITLE
[FEAT] 환경설정 > 버전정보 뷰 추가

### ISSUE THREAD

**Issue by KxxHyoRim** [TeamHavit/Havit-Android#849]
**📝 DESCRIPTION**
- Date : 2023.05.04

**☑ TODO**
- [ ] 릴리즈 전에는 버전 정보 확인이 어려워서 뷰 작업을 생략했는데, 이제는 추가하려 합니다!
- [ ] 업데이트 / 최신버전 / -(정보없음) 세가지 상태가 있습니다
- [ ] 업데이트 상태일 경우에는 클릭하면 play store로 이동합니다
- [ ] 정보없음의 경우에는 아래 두가지 가능성이 있습니다.
    1) Play Store를 제공하지 않는 에뮬레이터인 경우
    2) prod모드가 아닌 debug모드로 실행한 경우
<img width="336" alt="image" src="https://user-images.githubusercontent.com/59546818/235976471-23c8e40b-d516-4825-ac92-2bde5dd14da6.png">
