### ISSUE TITLE
[REFACTOR] 콘텐츠 저장 프로세스 코드 개선

### ISSUE THREAD

**Issue by KxxHyoRim** [TeamHavit/Havit-Android#863]
**📝 DESCRIPTION**
- Date : 2023.05.17

**☑ TODO**
- [ ] 이전에 제목을 저장할때 사용하던 `sharedPreference` 코드 정리하기
- [ ] `ShareActivity` - `BaseBindingActivity` 적용
- [ ] `ContentsActicity`에서 공유하기 누를시 **HAVIT으로도 공유 가능하게 변경**
**type**: _text/html_ -> _text/plain_으로 변경
