### ISSUE TITLE
[FEAT/UI] Create BottomSheetDialog of Category List in Contents View

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#89]
**📝 DESCRIPTION**
- Date : 2022.01.17

**☑ TODO**
- [x] 콘텐츠 뷰 상단 다이얼로그 ui였지만 앱잼 내에선 바텀시트로 하기로해, 해당 ui 제작
- [x] 프래그먼트 만들어서 액티비티에서 호출 및 mvvm 적용
- [x] 콘텐츠 뷰 카테고리 선택 기능 제작
