### ISSUE TITLE
[FIX] Android 13 Update & Deprecated된 onBackPressed 함수 제거 및 대처

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#891]
**📝 DESCRIPTION**
- Date : 2023.08.22

![image](https://github.com/TeamHavit/Havit-Android/assets/68214704/a027bcc2-2997-4dce-8a31-44ff6ff828d1)

Android 12를 타겟팅 하고 있어서 Android 13을 타겟팅 하도록 변경해야합니다.

**☑ TODO**
- [x] tagetSDK 31에서 33으로 변경
- [x] onBackPressed -> onBackPressedDispacher.addCallback 사용으로 변경
- [x] onBackPressedDispacher 사용을 위해 androidx version 1.6 이상으로 업데이트 (관련 url : https://heechokim.tistory.com/25)
