### ISSUE TITLE
[FEAT] Share Process

### ISSUE THREAD

**Issue by KxxHyoRim** [TeamHavit/Havit-Android#9]
**📝 DESCRIPTION**
- Date : 2020.01.12 ~ 2020.01.14
- Memo
   - 다른 뷰에서 bottom Sheet 재사용 가능하게 설정하는 방법 고민
   - 로그인 로직 고려

**☑ TODO**
- [x] 카테고리 제목 입력 fragment
- [x] 아이콘 선택 fragment
- [x] 카테고리 선택 fragment
- [x] 카테고리 추가 custom toast
- [x] 제목 수정 가운데 정렬
- [x] elipsize 속성 처리
- [x] 시간 설정 -> custom datepicker
- [x] 최종 저장 custom toast
