### ISSUE TITLE
[FEAT] set Contents list with server in HomeFragment, ContentsSimpleActivity

### ISSUE THREAD

**Issue by yubinquitous** [TeamHavit/Havit-Android#90]
**📝 DESCRIPTION**
- Date : 2022.01.17

**☑ TODO**
- [x] HomeFragment RecentContents 서버 연결
- [x] HomeFragment에서 보이는 ContentsList 10개로 가공
- [x] ContentsSimpleActivity RecentContents 서버 연결
- [x] ConetntsSimpleActivity UnseenContents 서버 연결
- [x] ContentsSimpleActivity에서 보이는 ContentsList 20개로 가공
