### ISSUE TITLE
[FEAT] 시스템 점검 중일 시 '시스템 점검중' 화면으로 이동

### ISSUE THREAD

**Issue by KxxHyoRim** [TeamHavit/Havit-Android#903]
**📝 DESCRIPTION**
- Date : 2023.12.1

**☑ TODO**
- [x] 시스템 점검중 Activity 추가
- [x] 앱 진입지점에서 시스템 점검중 화면으로 이동
    1. SplashActivity : 앱 아이콘 눌러서 들어오는 경우
    2. ShareActivity : 공유하기 눌러서 들어오는 경우
    3. WebActivity : 푸시알림 눌러서 들어오는 경우
- [x] 현재 진입지점에서만 분기를 만들어뒀기 때문에, 앱을 사용하는 도중에(ex. 콘텐츠뷰를 보던중) 서비스 점검중이 되면 '점검중'화면으로 넘어가지 않는 허점이 존재함. 추후 모든 화면에서 BaseActivity를 통한 분기처리를 하는 등의 방식으로 수정해야할 것 같음.
