### ISSUE TITLE
[FEAT] 커뮤니티 화면 제작

### ISSUE THREAD

**Issue by kimhyeing** [TeamHavit/Havit-Android#912]
**📝 DESCRIPTION**
- Date : 2024.03.20

**☑ TODO**
- [x] 커뮤니티 화면 제작
- [x] TabLayout + ViewPager2 적용한 홈, 커뮤니티 상단 탭 제작
- [x] 커뮤니티 카테고리 API 연동 및 카테고리 chip 동적 생성
- [x] 커뮤니티 글 작성 권유 tooltip close 버튼 클릭 시의 정보 SharedPreference에 저장 및 상태에 따라 visibility 처리
<img width="302" alt="image" src="https://github.com/TeamHavit/Havit-Android/assets/68214704/063658e7-9a39-4bab-aa9b-0565e36136e4">
