### ISSUE TITLE
[FEAT] 커뮤니티 생성 api 연동

### ISSUE THREAD

**Issue by KxxHyoRim** [TeamHavit/Havit-Android#931]
**📝 DESCRIPTION**
- Date : 2023.05.

**☑ TODO**
- [ ] 글 작성을 위한 하단 카테고리 get api 연동
- [ ] 글 작성 post api 연동
   - [ ]  ogData 크롤링 필요
   - [ ] url http 상태코드 확인 로직 viewmodel에서 분리
<img width="416" alt="image" src="https://github.com/TeamHavit/Havit-Android/assets/59546818/6023426a-38cc-4e62-bf4a-da9b184d1beb">
